import jsPDF from 'jspdf';
import { GeneratedStory } from '../types/story';

export const generatePDF = (story: GeneratedStory) => {
  const pdf = new jsPDF();
  
  // Set up fonts and styling
  pdf.setFontSize(20);
  pdf.setTextColor(30, 64, 175); // Greek blue
  pdf.text('Greek Story Generator', 20, 30);
  
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Topic: ${story.topic}`, 20, 45);
  pdf.text(`Grade Level: ${story.gradeLevel}`, 20, 55);
  pdf.text(`Length: ${story.length}`, 20, 65);
  
  // Add separator line
  pdf.setLineWidth(0.5);
  pdf.setDrawColor(220, 38, 38); // Terracotta
  pdf.line(20, 75, 190, 75);
  
  let yPosition = 90;
  const lineHeight = 15;
  const maxWidth = 170;
  
  story.pairs.forEach((pair, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = 30;
    }
    
    // Greek text (larger, bold)
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'bold');
    pdf.setTextColor(30, 64, 175);
    const greekLines = pdf.splitTextToSize(pair.greek, maxWidth);
    pdf.text(greekLines, 20, yPosition);
    yPosition += greekLines.length * lineHeight;
    
    // English text (smaller, normal)
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.setTextColor(100, 100, 100);
    const englishLines = pdf.splitTextToSize(pair.english, maxWidth);
    pdf.text(englishLines, 20, yPosition);
    yPosition += englishLines.length * lineHeight + 10;
  });
  
  // Add footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Generated by Greek Story Generator - Page ${i} of ${pageCount}`, 20, 280);
  }
  
  // Save the PDF
  pdf.save(`greek-story-${story.topic.replace(/\s+/g, '-').toLowerCase()}.pdf`);
};